WebApplication2/Models/STOCK_RECEIVED_NOTE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_RECEIVED_NOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK_RECEIVED_NOTE()
        {
            this.STOCK_RECEIVED_NOTE_DETAIL = new HashSet<STOCK_RECEIVED_NOTE_DETAIL>();
        }
    
        public int StockReceivedNoteID { get; set; }
        public System.DateTime StockReceivedNoteDate { get; set; }
        public int PublisherID { get; set; }
        public int ManagerID { get; set; }
    
        public virtual MANAGER MANAGER { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_RECEIVED_NOTE_DETAIL> STOCK_RECEIVED_NOTE_DETAIL { get; set; }
    }
}

WebApplication2/Areas/Manager/Controllers/STOCK_RECEIVED_NOTEController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Areas.Manager.Controllers

{
    [Authorize(Roles = "Manager")]
    public class STOCK_RECEIVED_NOTEController : Controller
    {
        private BookStoreManagerEntities db = new BookStoreManagerEntities();

        // GET: STOCK_RECEIVED_NOTE
        public ActionResult Index(string searchString, int? page, int? size, string sortOptions)
        {


            IQueryable<STOCK_RECEIVED_NOTE> stockResult = db.STOCK_RECEIVED_NOTE.Include(s => s.MANAGER).Include(s => s.PUBLISHER);
            //search
            if(!string.IsNullOrEmpty(searchString))
            {
                stockResult = stockResult.Where(s => s.PUBLISHER.PublisherName.Contains(searchString));
                ViewBag.keyword = searchString;
            }


            //sort order
            ViewBag.sortOptions = new SelectList(
                new[] {
                        new SelectListItem { Value = "newest", Text = "Mới nhất" },
                        new SelectListItem { Value = "oldest", Text = "Cũ nhất" },
                }
                , "Value", "Text");

            if (string.IsNullOrEmpty(sortOptions))
                sortOptions = "newest";
            switch (sortOptions)
            {
                case "newest":
                    stockResult = stockResult.OrderByDescending(b => b.StockReceivedNoteDate);
                    ViewBag.selectedSort = "newest";
                    break;
                case "oldest":
                    stockResult = stockResult.OrderBy(b => b.StockReceivedNoteDate);
                    ViewBag.selectedSort = "oldest";
                    break;
                default:
                    stockResult = stockResult.OrderByDescending(b => b.StockReceivedNoteDate);
                    ViewBag.selectedSort = "newest";
                    break;
            }

            // pagination
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });

            foreach (var item in items)
                if (item.Value == size.ToString()) item.Selected = true;
            ViewBag.size = items;
            ViewBag.currentSize = size;

            int pageSize = size ?? 10;
            int pageNumber = (page ?? 1);

            return View(stockResult.ToPagedList(pageNumber, pageSize));
        }

        // GET: STOCK_RECEIVED_NOTE/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Find(id);
            if (sTOCK_RECEIVED_NOTE == null)
            {
                return HttpNotFound();
            }
            return View(sTOCK_RECEIVED_NOTE);
        }

        // GET: STOCK_RECEIVED_NOTE/Create
        public ActionResult Create()
        {
            //ViewBag.PublisherID = new SelectList(db.PUBLISHERs, "PublisherID", "selectDataTextField");
            ViewBag.PublisherID = new SelectList(db.PUBLISHERs, "PublisherID", "PublisherID");
            ViewBag.havePublisher = db.PUBLISHERs.ToList();
            return PartialView("_CreatePartialView");
        }

        // POST: STOCK_RECEIVED_NOTE/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StockReceivedNoteID,StockReceivedNoteDate,PublisherID,ManagerID")] STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE)
        {
            if (ModelState.IsValid)
            {
                sTOCK_RECEIVED_NOTE.ManagerID = (db.MANAGERs.ToList())[0].ManagerID;
                db.STOCK_RECEIVED_NOTE.Add(sTOCK_RECEIVED_NOTE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sTOCK_RECEIVED_NOTE);
        }

        // GET: STOCK_RECEIVED_NOTE/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Find(id);
            if (sTOCK_RECEIVED_NOTE == null)
            {
                return HttpNotFound();
            }
            //ViewBag.PublisherID = new SelectList(db.PUBLISHERs, "PublisherID", "selectDataTextField", sTOCK_RECEIVED_NOTE.PublisherID);
            ViewBag.PublisherID = new SelectList(db.PUBLISHERs, "PublisherID", "PublisherID", sTOCK_RECEIVED_NOTE.PublisherID);
            ViewBag.StockDate = Custom.Custom_Function.ConvertDate(sTOCK_RECEIVED_NOTE.StockReceivedNoteDate);
            return PartialView("_EditPartialView", sTOCK_RECEIVED_NOTE);
        }

        // POST: STOCK_RECEIVED_NOTE/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StockReceivedNoteID,StockReceivedNoteDate,PublisherID,ManagerID")] STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE)
        {
            if (ModelState.IsValid)
            {
                STOCK_RECEIVED_NOTE s = db.STOCK_RECEIVED_NOTE.Find(sTOCK_RECEIVED_NOTE.StockReceivedNoteID);
                db.Entry(s).CurrentValues.SetValues(sTOCK_RECEIVED_NOTE);
                s.ManagerID = (db.MANAGERs.ToList())[0].ManagerID;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sTOCK_RECEIVED_NOTE);
        }

        // GET: STOCK_RECEIVED_NOTE/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Find(id);
            if (sTOCK_RECEIVED_NOTE == null)
            {
                return HttpNotFound();
            }
            return View(sTOCK_RECEIVED_NOTE);
        }

        // POST: STOCK_RECEIVED_NOTE/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Find(id);
            if (db.STOCK_RECEIVED_NOTE_DETAIL.Any(s => s.StockReceivedNoteID == id))
            {
                ViewBag.ErrorMessage = "Vui lòng xóa chi tiết của phiếu nhập này trước !";
                return PartialView("_ErrorMessagePartialView");
            }
            else
            {
                db.STOCK_RECEIVED_NOTE.Remove(sTOCK_RECEIVED_NOTE);
                db.SaveChanges();
            }
            return Json(new { redirectToAction = true, actionUrl = Url.Action("Index") });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/Controllers/STOCK_RECEIVED_NOTEController.cs
//using System;
//using System.Collections.Generic;
//using System.Data;
//using System.Data.Entity;
//using System.Linq;
//using System.Net;
//using System.Web;
//using System.Web.Mvc;
//using WebApplication2.Models;

//namespace WebApplication2.Controllers
//{
//    public class STOCK_RECEIVED_NOTEController : Controller
//    {
//        private BookStoreManagerEntities db = new BookStoreManagerEntities();

//        // GET: STOCK_RECEIVED_NOTE
//        public ActionResult Index()
//        {
//            var sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Include(s => s.MANAGER).Include(s => s.PUBLISHER);
//            return View(sTOCK_RECEIVED_NOTE.ToList());
//        }

//        // GET: STOCK_RECEIVED_NOTE/Details/5
//        public ActionResult Details(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Find(id);
//            if (sTOCK_RECEIVED_NOTE == null)
//            {
//                return HttpNotFound();
//            }
//            return View(sTOCK_RECEIVED_NOTE);
//        }

//        // GET: STOCK_RECEIVED_NOTE/Create
//        public ActionResult Create()
//        {
//            ViewBag.ManagerID = new SelectList(db.MANAGERs, "ManagerID", "AccountID");
//            ViewBag.PublisherID = new SelectList(db.PUBLISHERs, "PublisherID", "PublisherName");
//            return View();
//        }

//        // POST: STOCK_RECEIVED_NOTE/Create
//        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
//        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Create([Bind(Include = "StockReceivedNoteID,StockReceivedNoteDate,PublisherID,ManagerID")] STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE)
//        {
//            if (ModelState.IsValid)
//            {
//                sTOCK_RECEIVED_NOTE.ManagerID = (db.MANAGERs.ToList())[0].ManagerID;
//                db.STOCK_RECEIVED_NOTE.Add(sTOCK_RECEIVED_NOTE);
//                db.SaveChanges();
//                return RedirectToAction("Index");
//            }

//            ViewBag.ManagerID = new SelectList(db.MANAGERs, "ManagerID", "AccountID", sTOCK_RECEIVED_NOTE.ManagerID);
//            ViewBag.PublisherID = new SelectList(db.PUBLISHERs, "PublisherID", "PublisherName", sTOCK_RECEIVED_NOTE.PublisherID);
//            return View(sTOCK_RECEIVED_NOTE);
//        }

//        // GET: STOCK_RECEIVED_NOTE/Edit/5
//        public ActionResult Edit(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Find(id);
//            if (sTOCK_RECEIVED_NOTE == null)
//            {
//                return HttpNotFound();
//            }
//            ViewBag.ManagerID = new SelectList(db.MANAGERs, "ManagerID", "AccountID", sTOCK_RECEIVED_NOTE.ManagerID);
//            ViewBag.PublisherID = new SelectList(db.PUBLISHERs, "PublisherID", "PublisherName", sTOCK_RECEIVED_NOTE.PublisherID);
//            return View(sTOCK_RECEIVED_NOTE);
//        }

//        // POST: STOCK_RECEIVED_NOTE/Edit/5
//        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
//        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Edit([Bind(Include = "StockReceivedNoteID,StockReceivedNoteDate,PublisherID,ManagerID")] STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE)
//        {
//            if (ModelState.IsValid)
//            {
//                db.Entry(sTOCK_RECEIVED_NOTE).State = EntityState.Modified;
//                db.SaveChanges();
//                return RedirectToAction("Index");
//            }
//            ViewBag.ManagerID = new SelectList(db.MANAGERs, "ManagerID", "AccountID", sTOCK_RECEIVED_NOTE.ManagerID);
//            ViewBag.PublisherID = new SelectList(db.PUBLISHERs, "PublisherID", "PublisherName", sTOCK_RECEIVED_NOTE.PublisherID);
//            return View(sTOCK_RECEIVED_NOTE);
//        }

//        // GET: STOCK_RECEIVED_NOTE/Delete/5
//        public ActionResult Delete(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Find(id);
//            if (sTOCK_RECEIVED_NOTE == null)
//            {
//                return HttpNotFound();
//            }
//            return View(sTOCK_RECEIVED_NOTE);
//        }

//        // POST: STOCK_RECEIVED_NOTE/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public ActionResult DeleteConfirmed(int id)
//        {
//            STOCK_RECEIVED_NOTE sTOCK_RECEIVED_NOTE = db.STOCK_RECEIVED_NOTE.Find(id);
//            db.STOCK_RECEIVED_NOTE.Remove(sTOCK_RECEIVED_NOTE);
//            db.SaveChanges();
//            return RedirectToAction("Index");
//        }

//        protected override void Dispose(bool disposing)
//        {
//            if (disposing)
//            {
//                db.Dispose();
//            }
//            base.Dispose(disposing);
//        }
//    }
//}

WebApplication2/Areas/Manager/Views/STOCK_RECEIVED_NOTE/Delete.cshtml
@model WebApplication2.Models.STOCK_RECEIVED_NOTE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>STOCK_RECEIVED_NOTE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StockReceivedNoteDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StockReceivedNoteDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MANAGER.AccountID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MANAGER.AccountID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PUBLISHER.PublisherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PUBLISHER.PublisherName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication2/Areas/Manager/Views/STOCK_RECEIVED_NOTE/Details.cshtml
@model WebApplication2.Models.STOCK_RECEIVED_NOTE

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>STOCK_RECEIVED_NOTE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StockReceivedNoteDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StockReceivedNoteDate)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.PUBLISHER.PublisherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PUBLISHER.PublisherName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StockReceivedNoteID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication2/Areas/Manager/Views/STOCK_RECEIVED_NOTE/Index.cshtml
@model PagedList.IPagedList<WebApplication2.Models.STOCK_RECEIVED_NOTE>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}


<!--**********************************
            Content body start
        ***********************************-->
<div class="content-body">

    <div class="row page-titles mx-0">
        <div class="col p-md-0">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Dashboard","Home")">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="@Url.Action("Index","Stock_received_note")">Phiếu nhập</a></li>
            </ol>
        </div>
    </div>

    <div class="d-flex justify-content-end mr-4">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createModal">
            Thêm phiếu nhập mới
        </button>
    </div>
    <hr />

    <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Phiếu nhập</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="CreatePartialViewContainer">
                    <!-- The partial view will be loaded here -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Phiếu nhập</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="edit-modal-body modal-body ">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </div>
    </div>

    <!-- row -->
    @using (Html.BeginForm("Index", "STOCK_RECEIVED_NOTE", FormMethod.Get, new { @class = "form-inline justify-content-between" }))
    {
        <div class="form-group ml-5">
            <label>Tìm theo tên bộ sưu tập: </label>
            <input type="Text" class="form-control mx-sm-3" value="@ViewBag.Keyword" name="searchString" placeholder="">
            <input type="submit" class="btn btn-danger" value="Tìm kiếm">
        </div>
        <div class="form-group ml-auto mr-4">
            <label class="ml-2">Sắp xếp theo ngày nhập: </label>
            @Html.DropDownList("sortOptions", null, htmlAttributes: new { @class = "form-control  mx-sm-3", @onchange = "this.form.submit();" })
        </div>
        <hr />
    }


    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Danh sách phiếu nhập</h4>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered zero-configuration">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.First().StockReceivedNoteID)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.First().StockReceivedNoteDate)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.First().PUBLISHER.PublisherName)
                                        </th>
                                        <th>Thao tác</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.StockReceivedNoteID)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.StockReceivedNoteDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.PUBLISHER.PublisherName)
                                            </td>
                                            <td>
                                                <button type="button" class="btn btn-primary" id="@item.StockReceivedNoteID" data-toggle="modal" data-target="#editModal" value="@item.StockReceivedNoteID" onclick="loadPartialView(this.value)">
                                                    Chỉnh sửa
                                                </button>
                                                <button type="button" class="btn btn-primary" id="@item.StockReceivedNoteID" data-toggle="modal" data-target="#editModal" value="@item.StockReceivedNoteID" onclick="loadDetailsPartialView(this.value)">
                                                    Thêm chi tiết phiếu nhập
                                                </button>
                                                <button type="button" class="btn btn-dark" id="@item.StockReceivedNoteID" value="@item.StockReceivedNoteID" onclick="redirectToDetails(this.value)">
                                                    Thông tin chi tiết
                                                </button>

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <hr />
                            <div class="row">
                                <div class="col-md-6 col-lg-6 col-sm-6">
                                    @using (Html.BeginForm("Index", "stock_received_note", FormMethod.Get))
                                    {
                                        <p>
                                            Kích thước trang: @Html.DropDownList("size", null, new { @onchange = "this.form.submit();" })
                                        </p>
                                    }
                                </div>
                                <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right">
                                    Trang @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) / @Model.PageCount
                                </div>
                            </div>
                            @Html.PagedListPager(Model, page => Url.Action("Index", "stock_received_note", new { searchString = ViewBag.Keyword, page, size = ViewBag.currentSize, sortOptions = ViewBag.selectedSort }))
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #/ container -->
</div>
<!--**********************************
    Content body end
***********************************-->

<script>
    function loadCreatePartialView() {
        $.ajax({
            url: '/Manager/STOCK_RECEIVED_NOTE/Create',
            type: 'GET',
            success: function (data) {
                $('#CreatePartialViewContainer').html(data);
            },
            error: function () {
                $('#CreatePartialViewContainer').html("<p>Error loading partial view.</p>")
            }
        });
    }
    loadCreatePartialView();
</script>

<script>
    function redirectToDetails(stockReceivedNoteID) {
        var url = "/Manager/STOCK_RECEIVED_NOTE_DETAIL/Index/" + stockReceivedNoteID;
        window.location.href = url;
    }
</script>
<script>
    function loadPartialView(id) {
        $.ajax({
            url: '/Manager/STOCK_RECEIVED_NOTE/Edit',
            data: { id: id },
            type: 'GET',
            success: function (data) {
                $('.edit-modal-body').html(data);
            }
        });
    }
    function loadDetailsPartialView(id) {
        $.ajax({
            url: '/Manager/STOCK_RECEIVED_NOTE_DETAIL/CREATE',
            data: { stockReceivedNoteID: id },
            type: 'GET',
            success: function (data) {
                $('.edit-modal-body').html(data);
            }
        });
    }
</script>

WebApplication2/Areas/Manager/Views/STOCK_RECEIVED_NOTE/_CreatePartialView.cshtml
@model WebApplication2.Models.STOCK_RECEIVED_NOTE

@{
    ViewBag.Title = "Create";
}

<h2>Thêm mới</h2>

@if (ViewBag.havePublisher.Count == 0)
{
    <p style="color:red">Vui lòng thêm nhà xuất bản trước khi viết phiếu nhập</p>
}
else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Thông tin phiếu nhập</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.StockReceivedNoteDate, htmlAttributes: new { @class = "control-label col-md-10" })
                <div id="createDate" class="col-md-10">
                    <input type="datetime-local" id="StockReceivedNoteDate" name="StockReceivedNoteDate" required>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PublisherID, "Nhà xuất bản", htmlAttributes: new { @class = "control-label col-md-10" })
                <div class="col-md-10">
                    @Html.DropDownList("PublisherID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PublisherID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <script>
        $(document).ready(function () {
            var initial = new Date();
            initial.setHours(initial.getHours() + 7)
            $("#createDate").find("#StockReceivedNoteDate").val(initial.toISOString().slice(0, 16));
        });
        function updateMaxAttribute() {
            var currentDate = new Date();
            currentDate.setHours(currentDate.getHours() + 7);
            currentDate.setMinutes(currentDate.getMinutes());
            var currentDateString = currentDate.toISOString().slice(0, 16);
            $("#createDate").find("#StockReceivedNoteDate").prop("max", currentDateString);
        }
        setInterval(updateMaxAttribute, 1000);

    </script>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}