WebApplication2/Models/TIER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIER()
        {
            this.People = new HashSet<Person>();
        }
    
        public int TierID { get; set; }
        public string TierName { get; set; }
        public decimal TierDiscount { get; set; }
        public int TierLevel { get; set; }
        public int ManagerID { get; set; }
    
        public virtual MANAGER MANAGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
    }
}

WebApplication2/Areas/Manager/Controllers/TIERsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Areas.Manager.Controllers
{
    [Authorize(Roles = "Manager")]
    public class TIERsController : Controller
    {
        private BookStoreManagerEntities db = new BookStoreManagerEntities();

        // GET: TIERs
        public ActionResult Index(string searchString, int? page, int? size, string sortOptions)
        {
            IQueryable<TIER> tiers = db.TIERs;
            if (!string.IsNullOrEmpty(searchString))
            {
                string[] searchTerms = searchString.Split(' ');

                tiers = tiers.Where(p => searchTerms.All(term => p.TierName.Contains(term)));
                ViewBag.Keyword = searchString;
            }
            //sort order
            ViewBag.sortOptions = new SelectList(
                new[] {
                        new SelectListItem { Value = "newest", Text = "Mới nhất" },
                        new SelectListItem { Value = "oldest", Text = "Cũ nhất" },
                        new SelectListItem { Value = "range_asc", Text = "Cấp độ tăng dần" },
                        new SelectListItem { Value = "range_desc", Text = "Cấp độ giảm dần" }
                }
                , "Value", "Text");
            if (string.IsNullOrEmpty(sortOptions))
                sortOptions = "newest";
            switch (sortOptions)
            {
                case "newest":
                    tiers = tiers.OrderByDescending(b => b.TierID);
                    ViewBag.selectedSort = "newest";
                    break;
                case "oldest":
                    tiers = tiers.OrderBy(b => b.TierID);
                    ViewBag.selectedSort = "oldest";
                    break;
                case "range_asc":
                    tiers = tiers.OrderBy(b => b.TierLevel);
                    ViewBag.selectedSort = "range_asc";
                    break;
                case "range_desc":
                    tiers = tiers.OrderByDescending(b => b.TierLevel);
                    ViewBag.selectedSort = "range_desc";
                    break;
                default:
                    tiers = tiers.OrderByDescending(b => b.TierID);
                    ViewBag.selectedSort = "newest";
                    break;
            }

            // pagination
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });

            foreach (var item in items)
                if (item.Value == size.ToString()) item.Selected = true;
            ViewBag.size = items;
            ViewBag.currentSize = size;

            int pageSize = size ?? 10;
            int pageNumber = (page ?? 1);

            return View(tiers.ToPagedList(pageNumber, pageSize));

        }

        // GET: TIERs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIER tIER = db.TIERs.Find(id);
            if (tIER == null)
            {
                return HttpNotFound();
            }
            return View(tIER);
        }

        // GET: TIERs/Create
        public ActionResult Create()
        {
            ViewBag.usedName = db.TIERs.Select(t => t.TierName);
            return PartialView("_CreatePartialView");
        }

        // POST: TIERs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TierID,TierName,TierDiscount,TierLevel")] TIER tIER)
        {
            if (ModelState.IsValid)
            {
                if (db.TIERs.FirstOrDefault(b => b.TierName == tIER.TierName) != null)
                {
                    return RedirectToAction("Index");
                }
                tIER.ManagerID = (db.MANAGERs.ToList())[0].ManagerID;
                db.TIERs.Add(tIER);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tIER);
        }

        // GET: TIERs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIER tIER = db.TIERs.Find(id);
            if (tIER == null)
            {
                return HttpNotFound();
            }
            ViewBag.usedName = db.TIERs
                .Where(t => t.TierID != tIER.TierID)
                .Select(t => t.TierName);
            return PartialView("_EditPartialView", tIER);
        }

        // POST: TIERs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TierID,TierName,TierDiscount,TierLevel")] TIER tIER)
        {
            //note add the trigger when update tier
            if (ModelState.IsValid)
            {
                TIER t = db.TIERs.Find(tIER.TierID);
                db.Entry(t).CurrentValues.SetValues(tIER);
                t.ManagerID = (db.MANAGERs.ToList())[0].ManagerID;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tIER);
        }

        // GET: TIERs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TIER tIER = db.TIERs.Find(id);
            if (tIER == null)
            {
                return HttpNotFound();
            }
            return View(tIER);
        }

        // POST: TIERs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TIER tIER = db.TIERs.Find(id);
            db.TIERs.Remove(tIER);
            db.SaveChanges();
            return Json(new { redirectToAction = true, actionUrl = Url.Action("Index") });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication2/Controllers/TIERsController.cs
//using System;
//using System.Collections.Generic;
//using System.Data;
//using System.Data.Entity;
//using System.Linq;
//using System.Net;
//using System.Web;
//using System.Web.Mvc;
//using WebApplication2.Models;

//namespace WebApplication2.Controllers
//{
//    public class TIERsController : Controller
//    {
//        private BookStoreManagerEntities db = new BookStoreManagerEntities();

//        // GET: TIERs
//        public ActionResult Index()
//        {
//            var tIERs = db.TIERs.Include(t => t.MANAGER);
//            return View(tIERs.ToList());
//        }

//        // GET: TIERs/Details/5
//        public ActionResult Details(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            TIER tIER = db.TIERs.Find(id);
//            if (tIER == null)
//            {
//                return HttpNotFound();
//            }
//            return View(tIER);
//        }

//        // GET: TIERs/Create
//        public ActionResult Create()
//        {
//            return View();
//        }

//        // POST: TIERs/Create
//        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
//        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Create([Bind(Include = "TierID,TierName,TierDiscount,TierLevel")] TIER tIER)
//        {
//            if (ModelState.IsValid)
//            {
//                tIER.ManagerID = (db.MANAGERs.ToList())[0].ManagerID;
//                db.TIERs.Add(tIER);
//                db.SaveChanges();
//                return RedirectToAction("Index");
//            }
//            return View(tIER);
//        }

//        // GET: TIERs/Edit/5
//        public ActionResult Edit(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            TIER tIER = db.TIERs.Find(id);
//            if (tIER == null)
//            {
//                return HttpNotFound();
//            }
//            return View(tIER);
//        }

//        // POST: TIERs/Edit/5
//        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
//        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Edit([Bind(Include = "TierID,TierName,TierDiscount,TierLevel")] TIER tIER)
//        {
//            //note add the trigger when update tier
//            if (ModelState.IsValid)
//            {
//                TIER t = db.TIERs.Find(tIER.TierID);
//                db.Entry(t).CurrentValues.SetValues(tIER);
//                t.ManagerID = (db.MANAGERs.ToList())[0].ManagerID;
//                db.SaveChanges();
//                return RedirectToAction("Index");
//            }
//            return View(tIER);
//        }

//        // GET: TIERs/Delete/5
//        public ActionResult Delete(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            TIER tIER = db.TIERs.Find(id);
//            if (tIER == null)
//            {
//                return HttpNotFound();
//            }
//            return View(tIER);
//        }

//        // POST: TIERs/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public ActionResult DeleteConfirmed(int id)
//        {
//            TIER tIER = db.TIERs.Find(id);
//            if(tIER.People.Any())
//            {
//                ViewBag.message = "Failed. User is already linked with this tier";
//            }
//            else
//            {
//                db.TIERs.Remove(tIER);
//                db.SaveChanges();
//            }
//            return RedirectToAction("Index");
//        }

//        protected override void Dispose(bool disposing)
//        {
//            if (disposing)
//            {
//                db.Dispose();
//            }
//            base.Dispose(disposing);
//        }
//    }
//}

WebApplication2/Areas/Manager/Views/TIERs/Delete.cshtml
@model WebApplication2.Models.TIER

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TIER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TierDiscount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TierDiscount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TierLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TierLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MANAGER.AccountID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MANAGER.AccountID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication2/Areas/Manager/Views/TIERs/Details.cshtml
@model WebApplication2.Models.TIER

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TIER</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TierDiscount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TierDiscount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TierLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TierLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MANAGER.AccountID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MANAGER.AccountID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TierID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication2/Areas/Manager/Views/TIERs/Index.cshtml
@model PagedList.IPagedList<WebApplication2.Models.TIER>
@using PagedList.Mvc;
@{
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}


@{
    var currentModel = new WebApplication2.Models.TIER();
}

<!--**********************************
            Content body start
        ***********************************-->
<div class="content-body">

    <div class="row page-titles mx-0">
        <div class="col p-md-0">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="@Url.Action("Dashboard","Home")">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="@Url.Action("Index","Tiers")">Hạng người dùng</a></li>
            </ol>
        </div>
    </div>

    <div class="d-flex justify-content-end mr-4">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            Thêm hạng mới
        </button>
    </div>
    <hr />

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Hạng người dùng</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="CreatePartialViewContainer">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Hạng người dùng</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="edit-modal-body modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </div>
    </div>

    @using (Html.BeginForm("Index", "Tiers", FormMethod.Get, new { @class = "form-inline justify-content-between" }))
    {
        <div class="form-group ml-5">
            <label>Tên hạng: </label>
            <input type="Text" class="form-control mx-sm-3" value="@ViewBag.Keyword" name="searchString" placeholder="">
            <input type="submit" class="btn btn-danger" value="Tìm kiếm">
        </div>
        <div class="form-group ml-auto mr-4">
            <label class="ml-2">Sắp xếp theo: </label>
            @Html.DropDownList("sortOptions", null, htmlAttributes: new { @class = "form-control  mx-sm-3", @onchange = "this.form.submit();" })
        </div>
        <hr />
    }


    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Danh sách hạng</h4>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered zero-configuration">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.First().TierName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.First().TierDiscount)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.First().TierLevel)
                                        </th>
                                        @*<th>Thao tác</th>*@
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TierName)
                                            </td>
                                            <td>
                                                @((int)item.TierDiscount) %
                                            </td>
                                            <td>
                                                @item.TierLevel.ToString("#,##0").Replace(",", ".") VNĐ
                                            </td>
                                            @*<td>
                                                <button type="button" class="btn btn-primary" id="@item.TierID" data-toggle="modal" data-target="#editModal" value="@item.TierID" onclick="loadPartialView(this.value)">
                                                    Chỉnh sửa
                                                </button>

                                            </td>*@
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            @if (Model.PageCount > 1)
                            {
                                <hr />
                                <div class="row">
                                    <div class="col-md-6 col-lg-6 col-sm-6">
                                        @using (Html.BeginForm("Index", "Tiers", FormMethod.Get))
                                        {
                                            <p>
                                                Kích thước trang: @Html.DropDownList("size", null, new { @onchange = "this.form.submit();" })
                                            </p>
                                        }
                                    </div>
                                    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right">
                                        Trang @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) / @Model.PageCount
                                    </div>
                                </div>
                                @Html.PagedListPager(Model, page => Url.Action("Index", "Tiers", new { searchString = ViewBag.Keyword, page, size = ViewBag.currentSize, sortOptions = ViewBag.selectedSort }))
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #/ container -->
</div>
<!--**********************************
    Content body end
***********************************-->
<script src="~/Assets/Admin/js/jquery.js"></script>
<script>
    function loadCreatePartialView() {
        $.ajax({
            url: '/Manager/TIERs/Create',
            type: 'GET',
            success: function (data) {
                $('#CreatePartialViewContainer').html(data);
            },
            error: function () {
                $('#CreatePartialViewContainer').html("<p>Error loading partial view.</p>")
            }
        });
    }
    loadCreatePartialView();
</script>

<script>
    function loadPartialView(id) {
        $.ajax({
            url: '/Manager/TIERs/Edit',
            data: { id: id },
            type: 'GET',
            success: function (data) {
                $('.edit-modal-body').html(data);
            }
        });
    }
</script>

WebApplication2/Areas/Manager/Views/TIERs/_CreatePartialView.cshtml
@model WebApplication2.Models.TIER

@{
    ViewBag.Title = "Create";
}

<h2>Thêm mới</h2>


@using (Html.BeginForm("Create", "TIERs", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Thông tin hạng</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TierName, htmlAttributes: new { @class = "control-label col-md-10" })
        <div id="createDuplicate" class="col-md-10">
            @Html.EditorFor(model => model.TierName, new { htmlAttributes = new { @class = "form-control", @onchange="handleDuplicate()" , @required = "required" } })
            @Html.ValidationMessageFor(model => model.TierName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TierDiscount, htmlAttributes: new { @class = "control-label col-md-10 " })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TierDiscount, new { htmlAttributes = new { @class = "form-control" , @required = "required", type="number" } })
            @Html.ValidationMessageFor(model => model.TierDiscount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TierLevel, htmlAttributes: new { @class = "control-label col-md-10" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TierLevel, new { htmlAttributes = new { @class = "form-control" , @required = "required" } })
            @Html.ValidationMessageFor(model => model.TierLevel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="createButton" type="submit" value="Tạo" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        <div id="create-error-message">
        </div>
    </div>
</div>
}
<script>
    function handleDuplicate() {
        var tierName = $('#createDuplicate').find('#TierName').val();
        var listOfName = @Html.Raw(Json.Encode(ViewBag.usedName));

        if (listOfName != null && listOfName.includes(tierName)) {
            $('#create-error-message').html('<p style="color:red">Tên hạng bị trùng</p>')
            $('#createButton').prop('disabled', true);
        } else {
            $('#create-error-message').html('')
            $('#createButton').prop('disabled', false);
        }
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication2/Areas/Manager/Views/TIERs/_EditPartialView.cshtml
@model WebApplication2.Models.TIER

@{
    ViewBag.Title = "Edit";
}

<h2>Chỉnh sửa</h2>




@using (Html.BeginForm("Edit", "TIERs", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Thông tin hạng</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TierID)

    <div class="form-group">
        @Html.LabelFor(model => model.TierName, htmlAttributes: new { @class = "control-label col-md-10" })
        <div id="editDuplicate" class="col-md-10">
            @Html.EditorFor(model => model.TierName, new { htmlAttributes = new { @class = "form-control" , @onchange="handleDuplicate()" , @required = "required" } })
            @Html.ValidationMessageFor(model => model.TierName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TierDiscount, htmlAttributes: new { @class = "control-label col-md-10" })
        <div class="col-md-10">
            <input class="form-control" id="TierDiscount" , name="TierDiscount" value="@((int)Model.TierDiscount)" required type="number" />
            @Html.ValidationMessageFor(model => model.TierDiscount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TierLevel, htmlAttributes: new { @class = "control-label col-md-10" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TierLevel, new { htmlAttributes = new { @class = "form-control" , @required = "required" } })
            @Html.ValidationMessageFor(model => model.TierLevel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="editButton" type="submit" value="Lưu" class="btn btn-default" />
            <button type="button" class="btn btn-primary" onclick="loadController(@Model.TierID)">Xóa</button>
        </div>
    </div>

    <div class="form-group">
        <div id="edit-error-message">
        </div>
    </div>
</div>
}



<script>

    function loadController(id) {
        var userResponse = confirm("Ban sure chua?");
        if (userResponse == true) {
            var token = $('input[name="__RequestVerificationToken"]').val();
            $.ajax({
                url: '/Manager/TIERs/Delete',
                data: { id: id, __RequestVerificationToken: token },
                type: 'POST',
                success: function (data) {
                    if (data.redirectToAction) {
                        window.location.href = data.actionUrl;
                    }
                }
            });
        }

    }

</script>

<script>
    function handleDuplicate() {
        var tierName = $('#editDuplicate').find('#TierName').val();
        var listOfName = @Html.Raw(Json.Encode(ViewBag.usedName));
        console.log(tierName)
        console.log(listOfName)
        if (listOfName != null && listOfName.includes(tierName)) {
            $('#edit-error-message').html('<p style="color:red">Tên hạng bị trùng</p>')
            $('#editButton').prop('disabled', true);
        } else {
            $('#edit-error-message').html('')
            $('#editButton').prop('disabled', false);
        }
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}